"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {BossJob,filterByAppliedDate,isBossJobUrl,toCsv} from "./quest-utils";

type Stage="applied"|"first"|"second"|"final"|"offer";
type BattleStage=Exclude<Stage,"offer">;
type Quest={id:string;company:string;role:string;salary:string;sourceUrl:string;description:string;appliedAt:string;stage:Stage;stageAt:string;status:"active"|"failed";wins:Partial<Record<BattleStage,number>>};
type PrepType="forge"|"intel"|"power";
type Prep={id:string;title:string;note:string;type:PrepType;done:boolean;createdAt:string;completedAt:string|null};
const order:Stage[]=["applied","first","second","final","offer"];
const tabs:{key:BattleStage;label:string;art:string;hint:string}[]=[{key:"applied",label:"投递刷怪",art:"/monster-slime.png",hint:"普通怪"},{key:"first",label:"第一轮面试",art:"/monster-elite.png",hint:"精英怪 I"},{key:"second",label:"第二轮面试",art:"/monster-elite.png",hint:"精英怪 II"},{key:"final",label:"最终面试",art:"/monster-dragon.png",hint:"恶龙 BOSS"}];
const prepTypes:{key:PrepType;icon:string;title:string;subtitle:string;pos:string;art:string;power:number}[]=[{key:"forge",icon:"⚒",title:"装备锻造台",subtitle:"学习技能，参与项目与比赛",pos:"left",art:"/workshop-forge.png",power:3},{key:"intel",icon:"⌖",title:"战前情报室",subtitle:"企业信息与面试情报",pos:"center",art:"/workshop-intel.png",power:2},{key:"power",icon:"⚔",title:"攻击力训练场",subtitle:"简历优化、面试技巧与经验收集",pos:"right",art:"/workshop-training.png",power:3}];
const pad=(n:number)=>String(n).padStart(2,"0"),dayKey=(v:string)=>v.slice(0,10),timeLabel=(v:string)=>v.slice(11,16);
function nowLocal(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function dayLabel(v:string){const d=new Date(v+"T00:00:00"),n=new Date(),today=`${n.getFullYear()}-${pad(n.getMonth()+1)}-${pad(n.getDate())}`;const text=new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"short"}).format(d);return v===today?`今天 · ${text}`:text}
function dateTime(v:string|null){return v?new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—"}
function migrateQuest(raw:any):Quest|null{if(!raw||raw.stage==="rejected")return null;const stage:Stage=order.includes(raw.stage)?raw.stage:"applied",wins={...(raw.wins||{})};if(!raw.wins)order.slice(0,order.indexOf(stage)).forEach(s=>{if(s!=="offer")wins[s as BattleStage]=1});return {...raw,stage,stageAt:raw.stageAt||raw.appliedAt||nowLocal(),status:raw.status==="failed"?"failed":"active",salary:typeof raw.salary==="string"?raw.salary:"",sourceUrl:isBossJobUrl(raw.sourceUrl)?raw.sourceUrl:"",wins}}
function migratePrep(raw:any):Prep{const createdAt=raw.createdAt||nowLocal();return {...raw,createdAt,completedAt:raw.completedAt||(raw.done?createdAt:null)}}

export default function Home(){
 const [quests,setQuests]=useState<Quest[]>([]),[prep,setPrep]=useState<Prep[]>([]),[ready,setReady]=useState(false),[view,setView]=useState<"quests"|"workshop"|"offers">("quests"),[stage,setStage]=useState<BattleStage>("applied");
 const [openDays,setOpenDays]=useState<Record<string,boolean>>({}),[expanded,setExpanded]=useState<string|null>(null),[questModal,setQuestModal]=useState(false),[editingQuest,setEditingQuest]=useState<Quest|null>(null),[prepType,setPrepType]=useState<PrepType|null>(null),[editingPrep,setEditingPrep]=useState<Prep|null>(null),[rebirth,setRebirth]=useState(false),[bossModal,setBossModal]=useState(false),[bossReady,setBossReady]=useState(false),[bossLoading,setBossLoading]=useState(false),[bossMessage,setBossMessage]=useState(""),[questDefaults,setQuestDefaults]=useState<Partial<Quest>|null>(null),[exportModal,setExportModal]=useState(false);
 useEffect(()=>{try{setQuests(JSON.parse(localStorage.getItem("dragon-quests")||"[]").map(migrateQuest).filter(Boolean));setPrep(JSON.parse(localStorage.getItem("dragon-prep")||"[]").map(migratePrep))}catch{setQuests([]);setPrep([])}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("dragon-quests",JSON.stringify(quests))},[quests,ready]);useEffect(()=>{if(ready)localStorage.setItem("dragon-prep",JSON.stringify(prep))},[prep,ready]);
 const stageStats=useMemo(()=>Object.fromEntries(tabs.map(t=>[t.key,{success:quests.reduce((n,q)=>n+(q.wins[t.key]||0),0),failed:quests.filter(q=>q.stage===t.key&&q.status==="failed").length,active:quests.filter(q=>q.stage===t.key&&q.status==="active").length}])) as Record<BattleStage,{success:number;failed:number;active:number}>,[quests]);
 const stats=useMemo(()=>{const elite=["first","second"].reduce((n,s)=>{const x=stageStats[s as BattleStage];return n+x.success+x.failed+x.active},0),boss=Object.values(stageStats.final).reduce((a,b)=>a+b,0),power=prep.filter(p=>p.done).reduce((n,p)=>n+(prepTypes.find(t=>t.key===p.type)?.power||0),0);return{total:quests.length,eliteWin:stageStats.first.success+stageStats.second.success,bossWin:stageStats.final.success,offers:quests.filter(q=>q.stage==="offer").length,level:1+Math.floor(quests.length/20)+Math.floor(elite/2)+boss,progress:Math.min(95,(quests.length%20)*2+(elite%2)*15),power}},[quests,prep,stageStats]);
 const groups=useMemo(()=>{const m:Record<string,Quest[]>={};quests.filter(q=>q.stage==="applied").forEach(q=>(m[dayKey(q.appliedAt)]??=[]).push(q));return Object.entries(m).sort(([a],[b])=>b.localeCompare(a)).map(([date,items])=>({date,items:items.sort((a,b)=>b.appliedAt.localeCompare(a.appliedAt))}))},[quests]);
 const advance=(q:Quest)=>{const next=order[order.indexOf(q.stage)+1]||"offer";setQuests(all=>all.map(x=>x.id===q.id?{...x,wins:{...x.wins,[q.stage]:1},stage:next,stageAt:nowLocal(),status:"active"}:x));setExpanded(null)};
 const fail=(id:string)=>setQuests(all=>all.map(q=>q.id===id?{...q,status:"failed"}:q));
 const abandon=(id:string)=>{if(confirm("放弃将删除这条记录并减少一次征讨，确认继续？"))setQuests(all=>all.filter(q=>q.id!==id))};
 function saveQuest(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),sourceUrl=String(f.get("sourceUrl")||""),data={company:String(f.get("company")),role:String(f.get("role")),salary:String(f.get("salary")||""),sourceUrl:isBossJobUrl(sourceUrl)?sourceUrl:"",description:String(f.get("description")),appliedAt:String(f.get("appliedAt")),stageAt:String(f.get("stageAt")||f.get("appliedAt"))};if(editingQuest)setQuests(all=>all.map(q=>q.id===editingQuest.id?{...q,...data}:q));else setQuests(all=>[{id:crypto.randomUUID(),...data,stage:"applied",status:"active",wins:{}},...all]);setQuestModal(false);setEditingQuest(null);setQuestDefaults(null)}
 function savePrep(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),data={title:String(f.get("title")),note:String(f.get("note")),type:(f.get("type")||prepType) as PrepType};if(editingPrep)setPrep(all=>all.map(p=>p.id===editingPrep.id?{...p,...data}:p));else setPrep(all=>[{id:crypto.randomUUID(),...data,done:false,createdAt:nowLocal(),completedAt:null},...all]);setEditingPrep(null);setPrepType(null)}
 const togglePrep=(id:string)=>setPrep(all=>all.map(p=>p.id===id?{...p,done:!p.done,completedAt:!p.done?nowLocal():null}:p));
 const openNewQuest=(defaults:Partial<Quest>|null=null)=>{setEditingQuest(null);setQuestDefaults(defaults);setQuestModal(true)};
 async function openBoss(){setBossLoading(true);setBossReady(false);setBossMessage("");try{const response=await fetch("http://127.0.0.1:8000/api/health");if(!response.ok)throw new Error();const health=await response.json() as {extension_connected:boolean};setBossReady(health.extension_connected);setBossMessage(health.extension_connected?"提取器已就绪，请粘贴 BOSS 职位详情链接。":"本地服务已启动，但 Chrome 扩展尚未连接。")}catch{setBossMessage("无法连接本机 BOSS 提取器。请启动服务后重试。")}finally{setBossLoading(false);setBossModal(true)}}
 async function extractBoss(e:FormEvent<HTMLFormElement>){e.preventDefault();const url=String(new FormData(e.currentTarget).get("url")||"").trim();if(!isBossJobUrl(url)){setBossMessage("请输入有效的 BOSS 职位详情链接。");return}setBossLoading(true);try{const response=await fetch("http://127.0.0.1:8000/api/extract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const data=await response.json() as BossJob|{detail?:string};if(!response.ok)throw new Error("detail" in data?data.detail:"提取失败");const job=data as BossJob;setQuestDefaults({company:job.company_name,role:job.job_title,salary:job.salary,sourceUrl:job.source_url,description:job.job_description});setBossModal(false);setQuestModal(true)}catch(error){setBossMessage(error instanceof Error?error.message:"提取失败，请重试。")}finally{setBossLoading(false)}}
 const downloadExport=(start?:string,end?:string)=>{const items=filterByAppliedDate(quests,start,end),rows=[["投递时间","企业","岗位","薪资","当前阶段","状态","阶段时间","任务情报","BOSS 来源链接"],...items.map(q=>[q.appliedAt,q.company,q.role,q.salary,q.stage,q.status,q.stageAt,q.description,q.sourceUrl])],blob=new Blob(["\ufeff"+toCsv(rows)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a"),range=start&&end?`${start}至${end}`:start||end||"全部";link.href=url;link.download=`职位投递-${range}-${dayKey(nowLocal())}.csv`;link.click();URL.revokeObjectURL(url);setExportModal(false)}; const editQuest=(q:Quest)=>{setQuestDefaults(null);setEditingQuest(q);setQuestModal(true)};
 const reset=()=>{setQuests([]);setPrep([]);setView("quests");setStage("applied");setRebirth(false)};
 return <main>
  <header className="topbar"><div className="brand"><span className="brand-mark">⚔</span><div><b>猎职勇者团</b><small>DRAGON HUNT CAREER</small></div></div><nav><button className={view==="quests"?"active":""} onClick={()=>setView("quests")}>讨伐战报</button><button className={view==="workshop"?"active":""} onClick={()=>setView("workshop")}>勇者工坊</button><button className={view==="offers"?"active":""} onClick={()=>setView("offers")}>屠龙凭证</button></nav><div className="level"><span><small>LEVEL</small>LV.{pad(stats.level)}</span><div><b>无畏的求职者</b><i><em style={{width:stats.progress+"%"}}/></i><small>有效征讨与阶段挑战都会积累经验</small></div></div><button className="rebirth-button level-rebirth" onClick={()=>setRebirth(true)}>↻<small>重生</small></button></header>
  <section className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow">SEASON 01 · 求职远征</span><h1>今天，也向恶龙<br/><em>挥出一剑。</em></h1><p>每一次投递都是勇者踏出的新一步。记录讨伐，积累经验，直到拿下属于你的屠龙凭证。</p><button className="primary" onClick={()=>openNewQuest()}>＋ 接取新的讨伐任务</button></div><div className="hero-stats"><div><span>⚔</span><b>{stats.total}</b><small>累计征讨</small></div><div><span>♞</span><b>{stats.eliteWin}</b><small>精英胜利</small></div><div><span>♨</span><b>{stats.bossWin}</b><small>Boss 胜利</small></div><div><span>✦</span><b>{stats.offers}</b><small>屠龙凭证</small></div></div></section>
  <div className={`world-layout ${view==="workshop"?"workshop-world":view==="offers"?"honor-world":"quest-world"}`}><aside className="side-art"><img src={view==="workshop"?"/workshop-side-forge.png":view==="offers"?"/honor-side-left.png":"/equipment-side.png"} alt=""/></aside><section className="content">
  {view==="workshop"?<Workshop prep={prep} power={stats.power} add={setPrepType} open={setEditingPrep} toggle={togglePrep}/>:view==="offers"?<Offers quests={quests.filter(q=>q.stage==="offer")} edit={editQuest}/>:<><div className="quest-ledger-intro"><div className="section-head"><div><span className="section-kicker">QUEST LOG</span><h2>讨伐任务簿</h2><p>普通怪按日整理，精英怪与恶龙进入独立战场。</p></div><div className="export-tool"><button onClick={()=>setExportModal(true)}>导出</button></div><div className="count-medal"><b>{stats.total}</b><span>累计征讨</span></div></div><div className="stage-nav">{tabs.map(s=>{const n=stageStats[s.key];return <button key={s.key} className={stage===s.key?"on":""} onClick={()=>setStage(s.key)}><i><img src={s.art} alt=""/></i><span><b>{s.label}</b><small>{s.hint} · {n.active+n.failed}</small></span></button>})}</div></div>
  {stage==="applied"?<div className="daily-log">{groups.map((g,index)=>{const isOpen=openDays[g.date]??index===0;return <section className="day-group" key={g.date}><button className="day-head" onClick={()=>setOpenDays(v=>({...v,[g.date]:!isOpen}))}><span className="day-chevron">{isOpen?"−":"＋"}</span><div><h3>{dayLabel(g.date)}</h3><p>今日遭遇 {g.items.length} 只普通怪</p></div><strong>{g.items.length}<small> 次投递</small></strong></button>{isOpen&&<div className="day-rows">{g.items.map(q=><div className={`quest-row ${expanded===q.id?"expanded":""}`} key={q.id}><button className="row-main" onClick={()=>setExpanded(expanded===q.id?null:q.id)}><span className="slime">●</span><time>{timeLabel(q.appliedAt)}</time><b>{q.role}</b><span className="company">{q.company}</span><span className="row-status">已投递</span><span className="row-arrow">{expanded===q.id?"⌃":"⌄"}</span></button>{expanded===q.id&&<div className="row-detail"><div>{q.sourceUrl&&<a className="source-url" href={q.sourceUrl} target="_blank" rel="noopener noreferrer">来源职位：{q.sourceUrl}</a>}<small>任务情报</small><p className="quest-salary">薪资：{q.salary||"待补充"}</p><p>{q.description}</p></div><div className="row-actions"><button onClick={()=>editQuest(q)}>编辑</button><button className="advance" onClick={()=>advance(q)}>升级为一面精英 →</button><button onClick={()=>abandon(q.id)}>放弃</button></div></div>}</div>)}</div>}</section>})}{!groups.length&&<Empty text="还没有普通怪记录，接取一项新任务吧。"/>}</div>:<><BattleStats data={stageStats[stage]}/><div className="battle-grid">{quests.filter(q=>q.stage===stage).map(q=><BattleCard key={q.id} q={q} advance={advance} fail={fail} edit={editQuest}/>)}{!quests.some(q=>q.stage===stage)&&<Empty text="这个战场暂时安静。"/>}</div></>}</>}</section><aside className="side-art"><img src={view==="workshop"?"/workshop-side-intel.png":view==="offers"?"/honor-side-right.png":"/monsters-side.png"} alt=""/></aside></div>
  <footer className="atmosphere-footer"><div className="footer-copy"><span>✦ &nbsp; THE EXPEDITION CONTINUES &nbsp; ✦</span><h2>远征仍在继续</h2><p>沿着旧路，驶向下一场挑战。</p></div></footer>
  {questModal&&<Modal close={()=>{setQuestModal(false);setEditingQuest(null);setQuestDefaults(null)}} kicker={editingQuest?"EDIT QUEST":"NEW QUEST"} title={editingQuest?"编辑讨伐信息":"接取讨伐任务"}>{!editingQuest&&<button className="quest-extractor" type="button" onClick={openBoss}>BOSS 提取器</button>}<form onSubmit={saveQuest}><label>目标企业<input name="company" required defaultValue={editingQuest?.company||questDefaults?.company}/></label><label>挑战岗位<input name="role" required defaultValue={editingQuest?.role||questDefaults?.role}/></label><label>薪资<input name="salary" defaultValue={editingQuest?.salary||questDefaults?.salary}/></label><input name="sourceUrl" type="hidden" defaultValue={editingQuest?.sourceUrl||questDefaults?.sourceUrl||""}/><label>投递时间<input name="appliedAt" type="datetime-local" required defaultValue={editingQuest?.appliedAt||questDefaults?.appliedAt||nowLocal()}/></label>{editingQuest&&editingQuest.stage!=="applied"&&<label>征讨时间<input name="stageAt" type="datetime-local" required defaultValue={editingQuest.stageAt}/></label>}<label className="full">任务情报<textarea name="description" required defaultValue={editingQuest?.description||questDefaults?.description}/></label><button className="primary full" type="submit">{editingQuest?"保存修改":"⚔ 确认出征"}</button></form></Modal>}
  {bossModal&&<Modal close={()=>setBossModal(false)} kicker="BOSS EXTRACTOR" title="BOSS 提取器"><p className="modal-note">{bossMessage}</p><form onSubmit={extractBoss}><label className="full">职位详情链接<input name="url" type="url" placeholder="https://www.zhipin.com/job_detail/..." required disabled={!bossReady||bossLoading}/></label><button className="primary full" type="submit" disabled={!bossReady||bossLoading}>{bossLoading?"提取中...":"获取职位信息"}</button></form></Modal>}
  {exportModal&&<Modal close={()=>setExportModal(false)} kicker="EXPORT" title="导出投递信息"><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),start=String(data.get("startDate")||""),end=String(data.get("endDate")||"");downloadExport(start||undefined,end||undefined)}}><label>开始日期（可选）<input name="startDate" type="date"/></label><label>结束日期（可选）<input name="endDate" type="date"/></label><button className="primary full" type="submit">导出</button></form></Modal>}  {(prepType||editingPrep)&&<Modal close={()=>{setPrepType(null);setEditingPrep(null)}} kicker={editingPrep?"PREP DETAIL":"PREPARE"} title={editingPrep?"备战计划详情":"新增备战计划"}><form onSubmit={savePrep}>{editingPrep&&<label className="full">备战类型<select name="type" defaultValue={editingPrep.type}>{prepTypes.map(t=><option key={t.key} value={t.key}>{t.title}</option>)}</select></label>}<label className="full">计划名称<input name="title" required defaultValue={editingPrep?.title}/></label><label className="full">行动备注<textarea name="note" required defaultValue={editingPrep?.note}/></label>{editingPrep&&<div className="prep-time full"><span>创建于 {dateTime(editingPrep.createdAt)}</span>{editingPrep.completedAt&&<span>完成于 {dateTime(editingPrep.completedAt)}</span>}</div>}<button className="primary full" type="submit">{editingPrep?"保存修改":"加入备战清单"}</button>{editingPrep&&<button className="danger full" type="button" onClick={()=>{if(confirm("确认删除这项备战计划？")){setPrep(all=>all.filter(p=>p.id!==editingPrep.id));setEditingPrep(null)}}}>删除计划</button>}</form></Modal>}
  {rebirth&&<Modal close={()=>setRebirth(false)} kicker="REBIRTH" title="确认开启重生？"><div className="rebirth-confirm"><p>这会永久清空全部征讨与备战记录。</p><div><button onClick={()=>setRebirth(false)}>取消</button><button className="danger" onClick={reset}>确认重生</button></div></div></Modal>}
 </main>}

function BattleStats({data}:{data:{success:number;failed:number;active:number}}){return <div className="battle-stats"><span>胜 <b>{data.success}</b></span><span>败 <b>{data.failed}</b></span><span>进行中 <b>{data.active}</b></span></div>}
function BattleCard({q,advance,fail,edit}:{q:Quest;advance:(q:Quest)=>void;fail:(id:string)=>void;edit:(q:Quest)=>void}){const [open,setOpen]=useState(false),m=q.stage==="first"?{art:"/monster-elite.png",name:"一面精英",tone:"violet"}:q.stage==="second"?{art:"/monster-elite.png",name:"二面精英",tone:"violet"}:{art:"/monster-dragon.png",name:"恶龙 BOSS",tone:"red"};return <article className={`battle-card ${m.tone} ${open?"open":""} ${q.status==="failed"?"failed":""}`}><button className="battle-summary" onClick={()=>setOpen(v=>!v)}><div className="battle-top"><span><img src={m.art} alt=""/></span><b>{m.name}</b><time>{dateTime(q.stageAt)}</time></div><h3>{q.role}</h3><h4>{q.company}</h4>{q.status==="failed"&&<em className="failed-badge">挑战失败</em>}<div className="battle-toggle"><span>{open?"收起":"查看"}</span><i>{open?"−":"＋"}</i></div></button><div className="battle-detail"><div>{q.sourceUrl&&<a className="source-url" href={q.sourceUrl} target="_blank" rel="noopener noreferrer">来源职位：{q.sourceUrl}</a>}{q.salary&&<p className="quest-salary">薪资：{q.salary}</p>}<small>任务情报</small><p>{q.description}</p><div className="battle-actions"><button onClick={()=>edit(q)}>编辑</button>{q.status==="active"&&<><button className="advance" onClick={()=>advance(q)}>胜利，继续推进 →</button><button onClick={()=>fail(q.id)}>失败</button></>}</div></div></div></article>}
function Offers({quests,edit}:{quests:Quest[];edit:(q:Quest)=>void}){return <section className={`honor-scene ${quests.length%2?"odd":"even"}`}><div className="section-head"><div><span className="section-kicker">VICTORY ARCHIVE</span><h2>屠龙荣誉室</h2><p>每一份 Offer，都会被铸成属于勇者的屠龙奖章。</p></div></div><div className="offer-grid">{quests.map(q=><article className="offer-card" key={q.id}><img className="honor-medal" src="/honor-medal.png" alt="屠龙奖章"/><small>DRAGON SLAYER MEDAL</small><h3>{q.role}</h3><h4>{q.company}</h4>{q.salary&&<p className="quest-salary">薪资：{q.salary}</p>}{q.sourceUrl&&<a className="source-url" href={q.sourceUrl} target="_blank" rel="noopener noreferrer">来源职位：{q.sourceUrl}</a>}<p>{q.description}</p><button className="offer-edit" onClick={()=>edit(q)}>编辑</button></article>)}{!quests.length&&<Empty text="荣誉厅的展台正在等待第一枚屠龙奖章。"/>}</div></section>}
function Workshop({prep,power,add,open,toggle}:{prep:Prep[];power:number;add:(t:PrepType)=>void;open:(p:Prep)=>void;toggle:(id:string)=>void}){return <><div className="section-head workshop-heading"><div><span className="section-kicker">HERO'S WORKSHOP</span><h2>勇者工坊</h2><p>真正的胜负，在进入战场前就已经开始。</p></div></div><div className="power-panel"><span className="power-icon">⚔</span><div><small>当前综合攻击力</small><strong>{power}</strong></div><div className="power-track"><i><em style={{width:(power%30)/30*100+"%"}}/></i><small>距离下一战力里程碑</small></div></div><div className="workshop-grid">{prepTypes.map(t=><section className={`workshop ${t.pos}`} key={t.key}><div className="workshop-art"><img src={t.art} alt={t.title}/><button className="workshop-add" onClick={()=>add(t.key)}>＋</button><div className="workshop-title"><span>{t.icon}</span><div><h3>{t.title}</h3><p>{t.subtitle}</p></div></div></div><div className="prep-list">{prep.filter(p=>p.type===t.key).map(item=><div className={`prep-item ${item.done?"done":""}`} key={item.id} onClick={()=>open(item)}><button className="prep-check" onClick={e=>{e.stopPropagation();toggle(item.id)}}>{item.done?"✓":""}</button><div><b>{item.title}</b><small>{item.note}</small></div><span>›</span></div>)}{!prep.some(p=>p.type===t.key)&&<p className="no-prep">点击图片右上角添加</p>}</div></section>)}</div></>}
function Empty({text}:{text:string}){return <div className="empty"><span>♧</span><h3>暂无记录</h3><p>{text}</p></div>}
function Modal({close,kicker,title,children}:{close:()=>void;kicker:string;title:string;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className="section-kicker">{kicker}</span><h2>{title}</h2>{children}</div></div>}
